---
- name: Config_samba | Configuring samba
  ansible.builtin.template:
    src: etc/samba/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Restart nmbd
    - Restart smbd
