---
- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - samba
    - samba-common
  when: samba_from_os

- name: debian | Installing Packages When Domain Controller
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - krb5-config
    - krb5-user
    - libnss-winbind
    - libpam-winbind
    - winbind
  when: (samba_create_domain_controller and samba_from_os)
