---
- name: Domain_users | Generate list of users
  ansible.builtin.command: "samba-tool user list"
  register: domain_users
  changed_when: false

- name: Domain_users | Creating domain users
  ansible.builtin.command: "samba-tool user add {{ item['name'] }} '{{ item['password'] }}'"
  become: true
  changed_when: true
  with_items: "{{ samba_domain_users }}"
  when: item['name'] not in domain_users['stdout']
