---
- name: Join_domain | Checking if already joined to domain
  ansible.builtin.stat:
    path: /var/log/.samba_ad_joined
  register: samba_ad_join_check

- name: Join_domain | Joining domain
  ansible.builtin.shell: samba-tool domain join {{ samba_ad_info['ad_dns_domain_name'] }} DC --username="{{ samba_ad_info['netbios_domain_name'] | upper }}\administrator" --password="{{ samba_ad_info['adminpass'] }}" # noqa command-instead-of-shell yaml[line-length]
  become: true
  changed_when: true
  notify: Mark samba ad joined
  when: not samba_ad_join_check['stat']['exists']
