---
# tasks file for ansible-samba

- include_vars: debian.yml
  when: ansible_os_family == "Debian"

- include_vars: redhat.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: samba_groups.yml
  when: samba_groups is defined

- include: samba_users.yml
  when: samba_users is defined

- include: create_shares.yml
  when: samba_shares is defined

- include: config_samba.yml

- include: create_domain.yml
  when: >
    samba_create_domain_controller

- name: makesure samba service is running
  service:
    name: "{{ samba_samba_ad_service_name }}"
    state: started

- include: create_ou.yml
  when: samba_ous is defined

- include: join_domain.yml
  when: >
    samba_create_domain_controller and
    samba_domain_controllers_group is defined and
    inventory_hostname != samba_primary_domain_controller

- include: domain_users.yml
  tags:
    - samba_domain_account_management
    - samba_domain_users
  when: >
    samba_create_domain_users is defined and
    samba_create_domain_users and
    samba_domain_controllers_group is defined and
    inventory_hostname == samba_primary_domain_controller

- include: domain_groups.yml
  tags:
    - samba_domain_account_management
    - samba_domain_groups
  when: >
    samba_create_domain_groups is defined and
    samba_create_domain_groups and
    samba_domain_controllers_group is defined and
    inventory_hostname == samba_primary_domain_controller
