---
- name: enable yum repository
  yum_repository:
    name: tis-samba
    description: tis-samba
    baseurl: http://samba.tranquil.it/centos7/stable/
    gpgcheck: no
    enabled: yes

- name: install default packages of samba compile
  package:
    name: "{{ item }}"
  with_items:
    - krb5-workstation
    - samba
    - samba-winbind
    - samba-winbind-clients

- name: enabled systemd service
  systemd:
    enabled: yes
    name: "{{ item }}"
  with_items:
    - samba
