---
- name: Samba_users | Adding samba users to samba groups
  ansible.builtin.user:
    name: "{{ item[0]['name'] }}"
    groups: "{{ item[1] }}"
    append: yes
  become: true
  with_subelements:
    - "{{ samba_users }}"
    - groups

- name: Samba_users | Creating samba user passwords # noqa risky-shell-pipe
  ansible.builtin.shell: "(echo {{ item['smbpasswd'] }}; echo {{ item['smbpasswd'] }}) | smbpasswd -s -a {{ item['name'] }}"
  become: true
  changed_when: true
  with_items: "{{ samba_users }}"
