---
# handlers file for ansible-samba
- name: Mark samba ad joined
  ansible.builtin.file:
    path: /var/log/.samba_ad_joined
    state: touch
    mode: "0644"
  become: true

- name: Restart nmbd
  ansible.builtin.service:
    name: nmbd
    state: restarted
  become: true

- name: Restart samba-ad-dc
  ansible.builtin.service:
    name: samba-ad-dc
    state: restarted
  become: true

- name: Restart smbd
  ansible.builtin.service:
    name: smbd
    state: restarted
  become: true
