---
# handlers file for ansible-samba
- name: Restart nmbd
  ansible.builtin.service:
    name: nmbd
    state: restarted
  become: true

- name: Restart samba-ad-dc
  ansible.builtin.service:
    name: samba-ad-dc
    state: restarted
  become: true

- name: Restart smbd
  ansible.builtin.service:
    name: smbd
    state: restarted
  become: true
